export const stats = [
  "Minutes Played / Game",
  "Field Goals / Game",
  "Field Goals Attempted / Game",
  "Field Goal %",
  "3 Point Shots / Game",
  "3 Point Shots Attemped / Game",
  "3 Point %",
  "2 Point Field Goals / Game",
  "2 Point Field Goal Attempted / Game",
  "2 Point Field Goal %",
  "Effective Field Goal %",
  "Free Throw / Game",
  "Free Throw Attempted / Game",
  "Free Throw %",
  "Offensive Rebounds / Game",
  "Defensive Rebounds / Game",
  "Total Rebounds / Game",
  "Assists / Game",
  "Steals / Game",
  "Blocks / Game",
  "Turnovers / Game",
  "Personal Fouls / Game",
  "Points / Game",
  "Total Minutes Played",
  "Player Efficiency Rating (PER)",
  "True Shooting Percentage",
  "3 Point Attempt Rate",
  "Free Throw Attempt Rate",
  "Offensive Rebound Percentage",
  "Defensive Rebound Perentage",
  "Total Rebound Percentage",
  "Assist Percentage",
  "Steal Percentage",
  "Block Percentage",
  "Turnover Percentage",
  "Usage Percentage",
  "Offensive Win Shares",
  "Deffensive Win Shares",
  "Win Shares",
  "Win Shares / 48",
  "Offensive Box Plus Minus",
  "Deffensive Box Plus Minus",
  "Box Plus Minus",
  "Value Over Replacement Player (VORP)",
];
