let statDictionary = {
  "Minutes Played / Game": "mp_per_g",
  "Field Goals / Game": "fg_per_g",
  "Field Goals Attempted / Game": "fga_per_g",
  "Field Goal %": "fg_pct",
  "3 Point Shots / Game": "fg3_per_g",
  "3 Point Shots Attemped / Game": "fg3a_per_g",
  "3 Point %": "fg3_pct",
  "2 Point Field Goals / Game": "fg2_per_g",
  "2 Point Field Goal Attempted / Game": "fg2a_per_g",
  "2 Point Field Goal %": "fg2_pct",
  "Effective Field Goal %": "efg_pct",
  "Free Throw / Game": "ft_per_g",
  "Free Throw Attempted / Game": "fta_per_g",
  "Free Throw %": "ft_pct",
  "Offensive Rebounds / Game": "orb_per_g",
  "Defensive Rebounds / Game": "drb_per_g",
  "Total Rebounds / Game": "trb_per_g",
  "Assists / Game": "ast_per_g",
  "Steals / Game": "stl_per_g",
  "Blocks / Game": "blk_per_g",
  "Turnovers / Game": "tov_per_g",
  "Personal Fouls / Game": "pf_per_g",
  "Points / Game": "pts_per_g",
  "Total Minutes Played": "mp",
  "Player Efficiency Rating (PER)": "per",
  "True Shooting Percentage": "ts_pct",
  "3 Point Attempt Rate": "fg3a_per_fga_pct",
  "Free Throw Attempt Rate": "fta_per_fga_pct",
  "Offensive Rebound Percentage": "orb_pct",
  "Defensive Rebound Perentage": "drb_pct",
  "Total Rebound Percentage": "trb_pct",
  "Assist Percentage": "ast_pct",
  "Steal Percentage": "stl_pct",
  "Block Percentage": "blk_pct",
  "Turnover Percentage": "tov_pct",
  "Usage Percentage": "usg_pct",
  "Offensive Win Shares": "ows",
  "Deffensive Win Shares": "dws",
  "Win Shares": "ws",
  "Win Shares / 48": "ws_per_48",
  "Offensive Box Plus Minus": "obpm",
  "Deffensive Box Plus Minus": "dbpm",
  "Box Plus Minus": "bpm",
  "Value Over Replacement Player (VORP)": "vorp",
};

export const statVerbiage = (stat) => {
  return statDictionary[stat];
};
